import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const sourceRoot=root;
const read=(file)=>fs.readFileSync(path.join(root,file),'utf8');
const context={window:{}};
vm.runInNewContext(fs.readFileSync(path.join(sourceRoot,'content','core-rules.source.en.js'),'utf8'),context);
vm.runInNewContext(fs.readFileSync(path.join(sourceRoot,'content','core-rules.en.js'),'utf8'),context);
vm.runInNewContext(read('config.js'),context);
vm.runInNewContext(read('basic-content.js'),context);

const data=context.window.CORE_RULES,pdf=context.window.CORE_PDF_SOURCE,modules=context.window.CORE_LEARN_MODULES,basic=context.window.CORE_BASIC_LAYOUTS;
const sourceIds=[data.introduction.id,...data.groups.flatMap((group)=>group.sections.map((section)=>section.id))];
const studyIds=modules.flatMap((module)=>module.sections);
assert.deepEqual([...studyIds].sort(),[...sourceIds].sort(),'study path must include every source section exactly once');
assert.equal(new Set(studyIds).size,studyIds.length,'study path contains duplicate sections');
assert.equal(studyIds.length,26,'unexpected lesson count');
for(const id of studyIds){assert(pdf.sections[id]?.length,`${id} has no source pages`);assert(Object.hasOwn(pdf.rules,id),`${id} has no source rule collection`);}
assert.equal(Object.values(pdf.rules).flat().length,146,'unexpected structured rule count');
assert.equal(Object.keys(pdf.pages).length,88,'complete page transcript is required');
for(let page=1;page<=88;page++)assert(fs.existsSync(path.join(root,'assets','pages',`page-${String(page).padStart(2,'0')}.jpg`)),`missing rendered source page ${page}`);
const app=read('app.js'),html=read('index.html');
const designedIds=['introduction','core-concepts','datasheets','moving','making-attacks','attack-sequence','other-concepts'];
assert.deepEqual(Object.keys(basic),designedIds,'only the requested first seven lessons should have designed layouts');
assert(app.includes('CORE_BASIC_LAYOUTS'),'designed lesson data must be rendered');
assert(html.includes('basic-content.js'),'designed lesson content must load before the application');
assert(basic.introduction.paragraphs.length===7,'complete introduction prose is required');
assert(basic.datasheets.visuals.some((item)=>item.src.includes('datasheet-boyz')),'annotated datasheet visual is required');
assert(app.includes('renderDatasheetLesson'),'datasheet must use a dedicated annotated-key layout');
assert(app.includes("datasheet-number',number"),'datasheet text must visibly match markers 1-7');
assert(app.includes("datasheet-picture-button','PICTURE ↑'"),'every datasheet key needs a picture jump');
assert(app.includes('map.dataset.returnTarget=item.id'),'picture back action must remember its originating key');
assert.equal(basic.moving.visuals.length,4,'all requested movement diagrams are required');
assert.equal(basic['attack-sequence'].visuals.length,7,'attack sequence tables and examples are required');
assert(basic['other-concepts'].visuals.some((item)=>item.src.includes('visibility')),'visibility examples are required');
for(const layout of Object.values(basic))for(const visual of layout.visuals||[])assert(fs.existsSync(path.join(root,visual.src)),`missing source crop ${visual.src}`);
assert(app.includes('rule.text'),'source text must remain searchable');
assert(app.includes('pdf.pages[String(page)]'),'complete page transcripts must be rendered');
assert(!app.includes('sourceExcerpt'),'learning version must not truncate source rules');
assert(!app.includes('section.summary'),'learning version must not render authored section summaries');
assert(html.includes('Original pages'),'original PDF page view must be available');
assert(html.includes('Original PDF pages are the authoritative lesson content.'),'source boundary must be explicit');
assert(html.includes('Contents refers to an unavailable page 89.'),'missing source page 89 must be disclosed');
for(const file of ['config.js','basic-content.js','app.js','styles.css'])assert(fs.existsSync(path.join(root,file)),`missing ${file}`);
console.log(`QA passed: ${designedIds.length} designed lessons, ${studyIds.length} total lessons, 146 searchable rule records, 88 authoritative source pages.`);
